// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WypozyczalniaGier.Data;

#nullable disable

namespace WypozyczalniaGierWideo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WypozyczalniaGier.Models.Gra", b =>
                {
                    b.Property<int>("IdGry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGry"));

                    b.Property<decimal>("CenaZaDzien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Platforma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGry");

                    b.ToTable("Gry");
                });

            modelBuilder.Entity("WypozyczalniaGier.Models.Uzytkownik", b =>
                {
                    b.Property<int>("IdUzytkownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUzytkownika"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUzytkownika");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("WypozyczalniaGier.Models.Wypozyczenie", b =>
                {
                    b.Property<int>("IdWypozyczenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWypozyczenia"));

                    b.Property<DateTime>("DataWypozyczenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZwrotu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZwrotuRzeczywista")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdGry")
                        .HasColumnType("int");

                    b.Property<int>("IdUzytkownika")
                        .HasColumnType("int");

                    b.Property<decimal>("Kara")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Koszt")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdWypozyczenia");

                    b.HasIndex("IdGry");

                    b.HasIndex("IdUzytkownika");

                    b.ToTable("Wypozyczenia");
                });

            modelBuilder.Entity("WypozyczalniaGier.Models.Wypozyczenie", b =>
                {
                    b.HasOne("WypozyczalniaGier.Models.Gra", "Gra")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("IdGry");

                    b.HasOne("WypozyczalniaGier.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("IdUzytkownika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gra");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("WypozyczalniaGier.Models.Gra", b =>
                {
                    b.Navigation("Wypozyczenia");
                });

            modelBuilder.Entity("WypozyczalniaGier.Models.Uzytkownik", b =>
                {
                    b.Navigation("Wypozyczenia");
                });
#pragma warning restore 612, 618
        }
    }
}
